export default {
    UPDATE_DISPLAY: 'UPDATE_DISPLAY',
    SAVE_VALUE:'SAVE_VALUE',
    CLEAN_DISPLAY:'CLEAN_DISPLAY',
    CLEAN_DISPLAY_IN_NEXT_OPERATION:'CLEAN_DISPLAY_IN_NEXT_OPERATION',
    SET_OPERATION:'SET_OPERATION',
    CLEAN_OPERATION:'CLEAN_OPERATION',
    ENTRY_WITH_DECIMAL_NUMBERS:'ENTRY_WITH_DECIMAL_NUMBERS'
}
