export default {
    DISPLAY_UPDATE: 'DISPLAY_UPDATE',
    SAVE_VALUE: 'SAVE_VALUE',
    CLEAN_DISPLAY: 'CLEAN_DISPLAY',
    CLEAN_DISPLAY_NEXT_OPERATION: 'CLEAN_DISPLAY_NEXT_OPERATION',
    SET_OPERATION: 'SET_OPERATION',
    CLEAN_OPERATION: 'CLEAN_OPERATION',
    DECIMAL_MODE: 'DECIMAL_MODE'
}